name: innowi_task
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  go_router: 16.0.0
  retrofit: 4.4.2
  dio: 5.8.0+1
  built_value: 8.9.5
  json_annotation: 4.9.0
  freezed: 2.4.4
  pretty_dio_logger: 1.4.0
  get_it: 8.0.0
  flutter_bloc: 9.1.1
  flutter_hooks: 0.20.5
  cached_network_image: 3.4.0
  objectbox: 4.1.0
  objectbox_flutter_libs: 4.1.0
  path_provider: 2.1.5
  gap: 3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  retrofit_generator: 9.1.3
  build_runner: 2.4.13
  envied_generator: 1.0.0
  json_serializable: 6.8.0
  built_value_generator: 8.9.2
  freezed_annotation: 2.4.4
  objectbox_generator: 4.1.0

flutter:
  uses-material-design: true
